# Generated by Django 5.2 on 2025-04-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='duration',
            field=models.FloatField(),
        ),
    ]
