# Generated by Django 5.2 on 2025-04-10 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_alter_audiofile_options_alter_audiofile_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short name for the class (e.g., 'repetition')", max_length=50)),
                ('prompt', models.TextField(help_text="Full prompt text (e.g., 'speech with stuttering characterized by repeated sounds...')")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this prompt should be used in predictions')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority prompts will be used first if there are too many prompts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PredictionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('softmax_temperature', models.FloatField(default=0.1, help_text='Temperature for softmax (default: 0.1)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('min_segment_duration', models.FloatField(default=1.0, help_text='Minimum segment duration in seconds', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('max_segment_duration', models.FloatField(default=3.0, help_text='Maximum segment duration in seconds', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(30.0)])),
                ('silence_threshold_db', models.FloatField(default=15.0, help_text='Silence threshold in dB', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(60.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prediction Settings',
                'verbose_name_plural': 'Prediction Settings',
            },
        ),
    ]
